services:
  - docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t jojosewang/testDockerTravis:latest .
  - docker push jojosewang/testDockerTravis:latest
